MovieDetails test working and MovieDetailAvatars styling updated
matai-2019/watch-better pull request #161
Opened 2019-07-22 22:38 UTC by jennie-watson

Closes #157

2019-07-22 23:32 UTC, LogansRuin requested changes

2019-07-22 23:32 UTC, LogansRuin commented on src/components/MovieDetails.jsx
> +              <Typography variant="body2" style={{ marginTop: 30 }} gutterBottom>
This creates an error. In the console. Pretty sure I fixed this today. Can you do another pull from development?

2019-07-22 23:58 UTC, jennie-watson commented on src/components/MovieDetails.jsx
> +              <Typography variant="body2" style={{ marginTop: 30 }} gutterBottom>
I've changed the Typography to Box on MovieDetails and amended the MovieDetails test length which is now passing correctly.

2019-07-23 00:44 UTC, LogansRuin approved these changes

2019-07-23 00:49 UTC, merged